spring.application.name=trading-app-v2
spring.datasource.url=jdbc:postgresql://localhost:5432/trading_db
spring.datasource.username=postgres
spring.datasource.password=ryota3425
spring.datasource.driver-class-name=org.postgresql.Driver
# 警告を消し、OSIVを無効化する
spring.jpa.open-in-view=false